# Generated by Django 3.1.2 on 2021-03-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201208_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ethnicity',
            field=models.CharField(default='indian', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='speciality',
            field=models.TextField(default='bone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='medicaid_recepient',
            field=models.BooleanField(default=False),
        ),
    ]
