# Generated by Django 3.1.2 on 2021-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210329_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ethnicity',
            field=models.CharField(default='Asian', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seeker',
            name='ethnicity',
            field=models.CharField(default='Latino', max_length=20),
            preserve_default=False,
        ),
    ]
