# Generated by Django 3.1.2 on 2021-04-24 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210413_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsConsulting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='users.provider')),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='users.seeker')),
            ],
        ),
    ]
