# Generated by Django 3.1.2 on 2021-04-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_isconsulting'),
    ]

    operations = [
        migrations.AddField(
            model_name='isconsulting',
            name='date_removed',
            field=models.DateTimeField(default=None),
        ),
    ]
