# Generated by Django 3.1.2 on 2021-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210424_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isconsulting',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
