# Generated by Django 3.1.2 on 2021-04-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210424_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isconsulting',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='users.provider'),
        ),
        migrations.AlterField(
            model_name='isconsulting',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to='users.seeker'),
        ),
    ]
