# Generated by Django 3.1.2 on 2020-12-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201208_1423'),
        ('listings', '0002_auto_20201219_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.provider'),
        ),
    ]
