# Generated by Django 3.1.2 on 2020-12-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20201219_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='speciality',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
