# Generated by Django 3.1.2 on 2020-12-19 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201208_1423'),
        ('listings', '0004_auto_20201219_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
    ]
