# Generated by Django 3.1.2 on 2021-03-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20201225_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ethnicity',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='speciality',
        ),
    ]
