# Generated by Django 3.1.2 on 2021-03-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210325_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ethnicity',
            field=models.CharField(default='indian', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='speciality',
            field=models.TextField(default='bone'),
            preserve_default=False,
        ),
    ]
