# Generated by Django 3.1.2 on 2020-12-19 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20201208_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.seeker')),
                ('heartrate', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('steps', models.IntegerField()),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
