# Generated by Django 3.1.2 on 2020-12-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201208_1423'),
        ('healthdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seeker'),
        ),
    ]
