# Generated by Django 3.1.2 on 2021-03-23 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0002_auto_20201219_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='heartrate',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(210), django.core.validators.MinValueValidator(50)]),
        ),
    ]
