# Generated by Django 3.1.2 on 2021-05-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0004_facts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Facts',
            new_name='Fact',
        ),
    ]
