# Generated by Django 3.1.2 on 2021-05-12 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0005_auto_20210506_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='blood_pressure',
            field=models.IntegerField(default=70, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(180)]),
            preserve_default=False,
        ),
    ]
