# Generated by Django 3.1.2 on 2021-05-12 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0006_healthdata_blood_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(60)]),
        ),
    ]
