# Generated by Django 3.1.2 on 2021-05-16 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthdata', '0007_auto_20210512_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='blood_pressure',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(60)]),
        ),
    ]
